-- Research Evaluation's assessment of each change it detects on a paper (docs/EVALUATION-REVIEW-CHANGES.md)
create table alerts (
    id                   bigint generated by default as identity primary key,
    paper_id             uuid         not null references papers (id) on delete cascade,
    change_type          varchar(32)  not null,
    -- identifies the change, so a re-sent nudge can't store it twice
    change_key           varchar(512) not null,
    severity             varchar(16)  not null,
    description          text         not null,
    recommendation       text         not null,
    notice_doi           varchar(255),
    -- fetched_at of the first snapshot the change shows up in
    detected_at          timestamp with time zone not null,
    snapshot_id          bigint       not null,
    previous_snapshot_id bigint       not null,
    status               varchar(16)  not null default 'new',
    status_changed_at    timestamp with time zone,
    created_at           timestamp with time zone not null,
    constraint uq_alerts_paper_change unique (paper_id, change_key)
);

create index idx_alerts_paper_detected on alerts (paper_id, detected_at);
