-- The researcher's log of notes on an alert, e.g. what they did about it (docs/EVALUATION-REVIEW-CHANGES.md)
create table alert_notes (
    id         bigint generated by default as identity primary key,
    alert_id   bigint                   not null references alerts (id) on delete cascade,
    text       text                     not null,
    created_at timestamp with time zone not null
);

create index idx_alert_notes_alert on alert_notes (alert_id);
