-- one row per snapshot Updating sends, never updated or deleted: the history is what gets compared.
-- V4 rather than V2 so it still applies after V3 (alerts) whichever lands first.
create table background_metadata (
    snapshot_id         bigint generated by default as identity primary key,
    paper_id            uuid         not null references papers (id),
    doi                 varchar(255) not null,
    fetched_at          timestamp with time zone not null,
    openalex_id         varchar(64),
    title               text,
    publication_year    integer,
    -- null means the source didn't answer, never false
    is_retracted        boolean,
    in_doaj             boolean,
    journal_source_id   varchar(64),
    journal_source_type varchar(64),
    journal             text,
    issn_l              varchar(16),
    publisher           text,
    cited_by_count      integer,
    -- kept exactly as Updating sent them; storage never looks inside
    crossref_updates    text,
    authors             text,
    source_status       text         not null
);

create index idx_background_metadata_paper on background_metadata (paper_id, snapshot_id);
