-- One report per paper per nudge that stored new alerts: it groups those alerts and holds what
-- Research Evaluation's investigation fetched for them (docs/EVALUATION-INVESTIGATION.md)
create table reports (
    id              bigint generated by default as identity primary key,
    paper_id        uuid                     not null references papers (id) on delete cascade,
    -- investigating -> investigated (investigation done) -> assessed (impact done)
    status          varchar(16)              not null default 'investigating',
    created_at      timestamp with time zone not null,
    investigated_at timestamp with time zone,
    -- written by impact (a later plan); reserved now so a report is the evaluation's home from the start
    evaluation      text,
    recommendation  text,
    evaluated_at    timestamp with time zone
);

create index idx_reports_paper on reports (paper_id);

-- the report that grouped the alert; null until one does. Set null rather than cascade: an alert
-- outlives nothing but its paper, which deletes both anyway
alter table alerts add column report_id bigint references reports (id) on delete set null;

create index idx_alerts_paper_report on alerts (paper_id, report_id);

-- one fetched document (a notice, a new version, or the paper's current copy) per DOI per report
create table report_documents (
    id                       bigint generated by default as identity primary key,
    report_id                bigint                   not null references reports (id) on delete cascade,
    kind                     varchar(16)              not null,
    doi                      varchar(255)             not null,
    crossref_status          varchar(16)              not null,
    -- kept exactly as Research Evaluation sent it; storage never looks inside
    crossref_record          text,
    -- notices only: whether the notice's Crossref update-to names this paper
    update_to_includes_paper boolean,
    text_status              varchar(16)              not null,
    text                     text,
    text_truncated           boolean                  not null default false,
    pdf_status               varchar(16)              not null,
    file_key                 varchar(255),
    sha256                   varchar(64),
    pdf_source_url           text,
    created_at               timestamp with time zone not null,
    pdf_fetched_at           timestamp with time zone,
    -- a DOI is only ever one kind within a report, so it's stored (and downloaded) once
    constraint uq_report_documents_report_doi unique (report_id, doi)
);
